# SPDX-FileCopyrightText: 2026 The argocd-cmp-cdk8s-deno Authors
# SPDX-License-Identifier: Apache-2.0 OR MIT

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: repo-server-patch.yaml
